name: Upload Coverage Reports

on:
  workflow_dispatch:

jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Set the appropriate Java version
          distribution: 'adopt'

      - name: Build and Test with Maven
        run: mvn clean verify

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: cinnamon-croissant/curs-management-system
